---
name: "Setup Tree-sitter Environment"
description: "Installs Tree-sitter CLI and generates grammar"

runs:
  using: "composite"
  steps:
    - name: Install Tree-sitter CLI
      run: npm install -g tree-sitter-cli
      shell: bash

    - name: Generate Grammar
      run: npm run generate
      shell: bash
