---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint Code Base

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  Linter:
    name: PR Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      statuses: write # required to publish lint status checks on commits
      contents: read # required to check out the repository
      packages: read # required to read packages during linting

    steps:
      - name: Run PR Lint
        # https://github.com/ivuorinen/actions
        uses: ivuorinen/actions/pr-lint@6a8c40d9c5ff01b901d382b0ef86d432215aae2a # v2026.09.09
