---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Stale

on:
  schedule:
    - cron: "0 8 * * *" # Every day at 08:00
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read # required to read repository metadata
  packages: read # required to read packages
  statuses: read # required to read commit statuses

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  stale:
    name: 🧹 Clean up stale issues and PRs
    runs-on: ubuntu-latest

    permissions:
      contents: write # only for delete-branch option
      issues: write # required to comment on and close stale issues
      pull-requests: write # required to comment on and close stale PRs
    steps:
      - uses: ivuorinen/actions/stale@8395dad6b7d5d7d2e1d016cac1eede33ab404a3c # v2026.06.18
