---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: Stale

on:
  schedule:
    - cron: "0 8 * * *" # Every day at 08:00
  workflow_call:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  stale:
    name: 🧹 Clean up stale issues and PRs
    runs-on: ubuntu-latest

    permissions:
      issues: write # required to comment on and close stale issues
      pull-requests: write # required to comment on and close stale PRs
    steps:
      - uses: ivuorinen/actions/stale@6a8c40d9c5ff01b901d382b0ef86d432215aae2a # v2026.09.09
